[Interface]
PrivateKey = +HeFCEouiYm4E5/cR1vpAoFo00vGfA+CTQvDzBy6GFM=
ListenPort = 51820
Address = 10.0.99.114/32
[Peer]
PublicKey = eGY2yF5QFfM8FBo2e77bNZZf4VfOTzsNLKYt7hlwn3c=
AllowedIPs = 192.168.99.199/32
Endpoint = 178.63.72.227:36914
